### ISSUE TITLE
Not possible to specify http.Transport/http.Client

### ISSUE THREAD

**Issue by nothingmuch** [drewolson/testflight#7]
I need to inject an http.Transport into testflight's requester to send requests through a proxy for additional validation in tests.

I achieved this by making the server field of testflight.Requester public, and adding a Transport field that is used to create the http.Client, and then duplicated WithServer for our own purposes.

I suppose there should be a better solution to handle more general cases, if not I'd be happy to submit my simple patch.

**Comment by drewolson** [comment]
@nothingmuch sorry for the delayed response. Go ahead and submit a PR so that I can get a better idea of what you're proposing. I can't guarantee that I'll accept it, but if it looks generically reusable I'll pull it in.

**Comment by nothingmuch** [comment]
Hmm, the repo was not created a as a fork so I can't make a PR, but here is the relevant commit:

https://github.com/Thermeon/testflight/commit/2af1b3f3ceab8dbef7d391d8d405a270da63b39c

Note that I don't think this is appropriate for testflight itself, API wise it's pretty disappointing, it's just the simplest change that would allow me to do that

**Comment by drewolson** [comment]
Thanks for following up. For now, I'm going to close this issue. If I can come up with an unobtrusive way to do this, I'll consider adding it later.
